## Poner los paquetes usados aqui

In [14]:
%%writefile requirements.txt

pandas
numpy
matplotlib
seaborn
plotly
nbformat

Overwriting requirements.txt

In [15]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install -r requirements.txt

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (from -r requirements.txt (line 2)) (3.0.2)
Requirement already satisfied: numpy in .\.venv\Lib\site-packages (from -r requirements.txt (line 3)) (2.4.4)
Requirement already satisfied: matplotlib in .\.venv\Lib\site-packages (from -r requirements.txt (line 4)) (3.10.8)
Requirement already satisfied: seaborn in .\.venv\Lib\site-packages (from -r requirements.txt (line 5)) (0.13.2)
Requirement already satisfied: plotly in .\.venv\Lib\site-packages (from -r requirements.txt (line 6)) (6.7.0)
Collecting nbformat (from -r requirements.txt (line 7))
  Using cached nbformat-5.10.4-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas->-r requirements.txt (line 2)) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in .\.venv\Lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\.venv\Lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\.venv\Lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in .\.venv\Lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\.venv\Lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (26.0)
Requirement already satisfied: pillow>=8 in .\.venv\Lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (12.2.0)
Requirement already satisfied: pyparsing>=3 in .\.venv\Lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (3.3.2)
Requirement already satisfied: narwhals>=1.15.1 in .\.venv\Lib\site-packages (from plotly->-r requirements.txt (line 6)) (2.19.0)
Collecting fastjsonschema>=2.15 (from nbformat->-r requirements.txt (line 7))
  Using cached fastjsonschema-2.21.2-py3-none-any.whl.metadata (2.3 kB)
Collecting jsonschema>=2.6 (from nbformat->-r requirements.txt (line 7))
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in .\.venv\Lib\site-packages (from nbformat->-r requirements.txt (line 7)) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in .\.venv\Lib\site-packages (from nbformat->-r requirements.txt (line 7)) (5.14.3)
Collecting attrs>=22.2.0 (from jsonschema>=2.6->nbformat->-r requirements.txt (line 7))
  Downloading attrs-26.1.0-py3-none-any.whl.metadata (8.8 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=2.6->nbformat->-r requirements.txt (line 7))
  Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=2.6->nbformat->-r requirements.txt (line 7))
  Using cached referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=2.6->nbformat->-r requirements.txt (line 7))
  Downloading rpds_py-0.30.0-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: platformdirs>=2.5 in .\.venv\Lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat->-r requirements.txt (line 7)) (4.9.6)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 2)) (1.17.0)
Collecting typing-extensions>=4.4.0 (from referencing>=0.28.4->jsonschema>=2.6->nbformat->-r requirements.txt (line 7))
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Using cached nbformat-5.10.4-py3-none-any.whl (78 kB)
Using cached fastjsonschema-2.21.2-py3-none-any.whl (24 kB)
Downloading jsonschema-4.26.0-py3-none-any.whl (90 kB)
Downloading attrs-26.1.0-py3-none-any.whl (67 kB)
Using cached jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Using cached referencing-0.37.0-py3-none-any.whl (26 kB)
Downloading rpds_py-0.30.0-cp312-cp312-win_amd64.whl (240 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: fastjsonschema, typing-extensions, rpds-py, attrs, referencing, jsonschema-specifications, jsonschema, nbformat

   ---------------------------------------- 0/8 [fastjsonschema]
   ----- ---------------------------------- 1/8 [typing-extensions]
   ---------- ----------------------------- 2/8 [rpds-py]
   --------------- ------------------------ 3/8 [attrs]
   --------------- ------------------------ 3/8 [attrs]
   -------------------- ------------------- 4/8 [referencing]
   -------------------- ------------------- 4/8 [referencing]
   ------------------------- -------------- 5/8 [jsonschema-specifications]
   ------------------------------ --------- 6/8 [jsonschema]
   ------------------------------ --------- 6/8 [jsonschema]
   ------------------------------ --------- 6/8 [jsonschema]
   ----------------------------------- ---- 7/8 [nbformat]
   ----------------------------------- ---- 7/8 [nbformat]
   ----------------------------------- ---- 7/8 [nbformat]
   ----------------------------------- ---- 7/8 [nbformat]
   ---------------------------------------- 8/8 [nbformat]

Successfully installed attrs-26.1.0 fastjsonschema-2.21.2 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 nbformat-5.10.4 referencing-0.37.0 rpds-py-0.30.0 typing-extensions-4.15.0

In [2]:
# Importamos las librerias
import pandas as pd
import matplotlib as plt
import numpy as np
import plotly.express as px
import seaborn as sea

from IPython.display import display

### Vamos a visualizar los datos!!

In [3]:
data = pd.read_csv("data/healthcare_tp.csv")

display(data.head())
display(data.tail())

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Discharge Date,Admission Type,Billing Amount,Medication,Test Results,Insurance Provider,Insurance Plan
0,56,Female,A+,Hypertension,2023-07-13,2023-07-16,Emergency,5374.88,Aspirin,Abnormal,Aetna,Gold
1,38,Male,A+,Obesity,2024-01-25,2024-02-06,Elective,1986.98,Orlistat,Abnormal,Cigna,Gold
2,56,Male,A+,Asthma,2024-07-30,2024-08-02,Emergency,6086.36,Inhaler,Abnormal,Blue Cross,Gold
3,42,Female,A+,Diabetes,2023-03-29,2023-04-06,Emergency,3589.38,Metformin,Abnormal,Aetna,Gold
4,54,Male,O+,Diabetes,2023-11-03,2023-11-13,Elective,2600.54,Insulin,Inconclusive,Aetna,Basic

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Discharge Date,Admission Type,Billing Amount,Medication,Test Results,Insurance Provider,Insurance Plan
5995,44,Female,A+,Healthy,2024-08-21,2024-08-31,Emergency,3788.63,NaN,Normal,Medicare,Gold
5996,55,Male,O-,Obesity,2023-06-22,2023-06-29,Elective,2831.81,Orlistat,Normal,Cigna,Silver
5997,64,Female,A+,Diabetes,2024-01-07,2024-01-14,Elective,2588.33,Metformin,Inconclusive,Blue Cross,Platinum
5998,13,Female,O+,Obesity,2023-11-09,2023-11-20,Elective,1523.96,Orlistat,Abnormal,Cigna,Silver
5999,75,Male,B+,Hypertension,2023-08-10,2023-08-19,Elective,3736.62,Aspirin,Abnormal,Medicare,Gold

### Cuantos son hombres y mujeres

In [6]:
# hay que normalizar los datos antes de hacer la estadistica
data["Gender"] = data["Gender"].str.strip().str.lower()

# Conteo de hombres y mujeres
conteo_genero = (
    data["Gender"]
    .value_counts()
    .reset_index()
)
conteo_genero.columns = ["Gender", "Cantidad"]

# Pie chart interactivo
fig = px.pie(
    conteo_genero,
    names="Gender",
    values="Cantidad",
    title="Distribución por género",
    hole=0.4  # opcional: dona
)

fig.update_traces(textposition="inside", textinfo="percent+label")
fig.show()