## Poner los paquetes usados aqui

In [3]:
%%writefile requirements.txt

pandas
numpy
matplotlib
seaborn
plotly

Overwriting requirements.txt

In [4]:
# Install a pip package in the current Jupyter kernel
import sys
!{sys.executable} -m pip install -r requirements.txt

Requirement already satisfied: pandas in .\.venv\Lib\site-packages (from -r requirements.txt (line 2)) (3.0.2)
Requirement already satisfied: numpy in .\.venv\Lib\site-packages (from -r requirements.txt (line 3)) (2.4.4)
Requirement already satisfied: matplotlib in .\.venv\Lib\site-packages (from -r requirements.txt (line 4)) (3.10.8)
Requirement already satisfied: seaborn in .\.venv\Lib\site-packages (from -r requirements.txt (line 5)) (0.13.2)
Requirement already satisfied: plotly in .\.venv\Lib\site-packages (from -r requirements.txt (line 6)) (6.7.0)
Requirement already satisfied: python-dateutil>=2.8.2 in .\.venv\Lib\site-packages (from pandas->-r requirements.txt (line 2)) (2.9.0.post0)
Requirement already satisfied: tzdata in .\.venv\Lib\site-packages (from pandas->-r requirements.txt (line 2)) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in .\.venv\Lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\.venv\Lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\.venv\Lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in .\.venv\Lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\.venv\Lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (26.0)
Requirement already satisfied: pillow>=8 in .\.venv\Lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (12.2.0)
Requirement already satisfied: pyparsing>=3 in .\.venv\Lib\site-packages (from matplotlib->-r requirements.txt (line 4)) (3.3.2)
Requirement already satisfied: narwhals>=1.15.1 in .\.venv\Lib\site-packages (from plotly->-r requirements.txt (line 6)) (2.19.0)
Requirement already satisfied: six>=1.5 in .\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 2)) (1.17.0)

In [10]:
# Importamos las librerias
import pandas as pd
import matplotlib as plt
import numpy as np
import plotly as plty
import seaborn as sea

from IPython.display import display

### Vamos a visualizar los datos!!

In [11]:
data = pd.read_csv("data/healthcare_tp.csv")

display(data.head())
display(data.tail())

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Discharge Date,Admission Type,Billing Amount,Medication,Test Results,Insurance Provider,Insurance Plan
0,56,Female,A+,Hypertension,2023-07-13,2023-07-16,Emergency,5374.88,Aspirin,Abnormal,Aetna,Gold
1,38,Male,A+,Obesity,2024-01-25,2024-02-06,Elective,1986.98,Orlistat,Abnormal,Cigna,Gold
2,56,Male,A+,Asthma,2024-07-30,2024-08-02,Emergency,6086.36,Inhaler,Abnormal,Blue Cross,Gold
3,42,Female,A+,Diabetes,2023-03-29,2023-04-06,Emergency,3589.38,Metformin,Abnormal,Aetna,Gold
4,54,Male,O+,Diabetes,2023-11-03,2023-11-13,Elective,2600.54,Insulin,Inconclusive,Aetna,Basic

,Age,Gender,Blood Type,Medical Condition,Date of Admission,Discharge Date,Admission Type,Billing Amount,Medication,Test Results,Insurance Provider,Insurance Plan
5995,44,Female,A+,Healthy,2024-08-21,2024-08-31,Emergency,3788.63,NaN,Normal,Medicare,Gold
5996,55,Male,O-,Obesity,2023-06-22,2023-06-29,Elective,2831.81,Orlistat,Normal,Cigna,Silver
5997,64,Female,A+,Diabetes,2024-01-07,2024-01-14,Elective,2588.33,Metformin,Inconclusive,Blue Cross,Platinum
5998,13,Female,O+,Obesity,2023-11-09,2023-11-20,Elective,1523.96,Orlistat,Abnormal,Cigna,Silver
5999,75,Male,B+,Hypertension,2023-08-10,2023-08-19,Elective,3736.62,Aspirin,Abnormal,Medicare,Gold